# Generated by Django 4.2.6 on 2023-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('C', 'Культура'), ('B', 'Бизнес'), ('S', 'Наука'), ('N', 'Спорт'), ('T', 'Путешествия'), ('W', 'Погода')], max_length=25, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
